# Generated by Django 3.1.7 on 2021-06-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210611_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('✅', 'COMPLETE'), ('🕒', 'PENDING')], max_length=2),
        ),
    ]
